# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "kubernetes-gke"
box_name: "bento/ubuntu-20.04"
user: "vagrant"
cpus: 1
memory_size: 2048
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
time_zone: "America/New_York"
log_output: "/var/log/bootstrap.log"
