version: "2.1"
jobs:
  gate-job:
    docker:
      - image: circleci/golang:1.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download -x
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            go test -v -timeout 30m > /tmp/test_result_file.txt
      - store_artifacts:
          path: /tmp/test_result_file.txt
          destination: test_result_file
  format-root-module:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    environment:
      TF_CLI_ARGS: "-no-color"
      TF_IN_AUTOMATION: "true"
    steps:
      - checkout
    run:
      name: terraform format
      command: |
        terraform fmt -check
  check-job:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    environment:
      TF_CLI_ARGS: "-no-color"
      TF_IN_AUTOMATION: "true"
    working_directory: ~/kubernetes-gke/examples/complete
    steps:
      - checkout:
          path: ~/kubernetes-gke
      # - restore_cache:
      #     keys:
      #       - terraform-init-v4-{{ checksum ".terraform.lock.hcl" }}
      - run:
          name: terraform init
          command: |
            terraform fmt -check
            terraform init -input=false
      - save_cache:
          key: terraform-init-v4-{{ checksum ".terraform.lock.hcl" }}
          paths:
            - ".terraform"
      - run:
          name: terraform validate
          command: cd examples/completterraform validate
      - run:
          name: terraform plan
          command: terraform plan -out tfplan -var-file fixtures.tfvars
      - store_artifacts:
          path: tfplan
          destination: tfplan
workflows:
  terraform-workflow:
    jobs:
      - check-job
      - format-root-module
      - gate-job:
          requires:
            - check-job
          filters:
            branches:
              only:
                - develop
